project_name: 'WGS_Epistasis'
# short read raw-data
raw_data_path: '/data/jzhang/project/WGS_Epistasis_2025.10.17/00.raw_data'
# short read samples info
sample_csv: '/data/jzhang/project/WGS_Epistasis_2025.10.17/workflow/sample.csv'