[package]
name = "md5_checker_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rayon = "1.8"
md5 = "0.7"
log = "0.4"
fern = "0.6"
chrono = "0.4"
anyhow = "1.0"
csv = "1.3"
indicatif = { version = "0.17", features = ["rayon"] }