# reference & index
genome: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
bwa_index_path: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
bwa_mem2:
  index: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
  PL: DNB
qualimap:
  genome_gff: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.gff
  format: HTML
  mem: 20000M
samtools_stats:
  reference: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
fastq_screen:
  run: true
  path: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen
  conf: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen.conf
  subset: 100000
  aligner: Bowtie2
bcftools:
  path: /home/jzhang/software/bcftools-1.22/bcftools
  reference: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
# software
software:
  sambamba: /home/jzhang/software/tools/sambamba-1.0.1
# raw_data qc
checkmd5:
  name: MD5.txt
trim:
  length_required: 75
  quality_threshold: 25
  adapter_fasta: "./data/Universal_Adapter.fa"
# analysis resource
threads:
  md5_check: 10
  bwa_mem2: 10
  samtools: 10
  fastp: 5
  qualimap: 10
  qualimap: 10
  samtools_flagstat: 10
  samtools_stats: 10
  fastq_screen: 10
  bcftools: 10
# other parameter
print_target: true
log_level: INFO
bam_remove: true
convert_md5: 'link_dir'
r1_suffix: _R1.fq.gz
r2_suffix: _R2.fq.gz
md5: MD5.txt