# reference & index
genome: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
bwa_index_path: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
bwa_index: true
bwa_mem2:
  index: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
qualimap:
  genome_gff: /data/jzhang/reference/Lactuca_sativa_V11/data/jzhang/reference/Lactuca_sativa_V11
  format: HTML
samtools_stats:
  reference: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.fasta
# software
software:
  sambamba: 
# raw_data qc
checkmd5:
  name: MD5.txt
trim:
  length_required: 75
  quality_threshold: 25
  adapter_fasta: "./data/Universal_Adapter.fa"
# analysis resource
threads:
  md5_check: 10
  bwa_mem2: 10
  samtools: 10
  fastp: 5
  qualimap: 10
  qualimap: 10
  samtools_flagstat: 10
  samtools_stats: 10
# other parameter
print_target: true
log_level: INFO